# Generated by Django 5.1.6 on 2025-03-02 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.CharField(default='test', max_length=600),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='identifier',
            field=models.CharField(default='xxx-1', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conto',
            name='identifier',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='identifier',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='image',
            unique_together={('url', 'machine')},
        ),
    ]
